name: ci-docs

on:
  push:
    branches: main

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool update -g docfx

    - name: Add DocFX to PATH
      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

    - name: Build documentation
      run: docfx docs/docfx.json

    - uses: actions/upload-pages-artifact@v3
      with:
        path: artifacts/_site

  publish-docs:
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
